<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>  <!-- rebuild -->

    <parent>
        <groupId>com.sparkutils</groupId>
        <artifactId>kogito-4-spark_root_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>kogito-4-spark_shared_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>

    <packaging>jar</packaging>
    <name>Kogito 4 Spark Shared</name>
    <description>A Kogito implementation for the dmn-4-spark API</description>

    <dependencies>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scalaVersion}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>kogito_shaded</artifactId>
            <version>${shadedKogitoVersion}</version>
            <!--
            <exclusions>
                <exclusion>
                    <groupId>org.antlr</groupId>
                    <artifactId>antlr4-runtime</artifactId> <! - - 4.10.1 from here, 4.9.3 needed by spark - ->
                </exclusion>
            </exclusions>-->
        </dependency>

        <dependency>
            <groupId>com.sparkutils</groupId>
            <artifactId>dmn-4-spark_${dbrCompatVersion}${sparkCompatVersion}_${scalaCompatVersion}</artifactId>
            <version>${dmn4SparkVersion}</version>
        </dependency>
    </dependencies>

    <build>

        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
            </plugin>
        </plugins>

    </build>

</project>
